### ISSUE TITLE
Compilation Errors (setup.s43)

### ISSUE THREAD

**Issue by GRFroman** [kenneth-rosario/bpm-logging-simulation-msp430fr6989#12]
There were compilation errors in my copy of the main branch. These errors were the following: 
![image](https://user-images.githubusercontent.com/42808229/115151302-4587b100-a03a-11eb-8193-517a8ed07d4c.png)

![image](https://user-images.githubusercontent.com/42808229/115151309-559f9080-a03a-11eb-9b56-2d964c9a8062.png)

![image](https://user-images.githubusercontent.com/42808229/115151326-64864300-a03a-11eb-9629-b79a2d8b870d.png)

![image](https://user-images.githubusercontent.com/42808229/115151363-8b447980-a03a-11eb-853e-893562c91230.png)

**Comment by kenneth-rosario** [comment]
Did you set the correct msp in the IAR settings?
